#!/data/data/com.termux/files/usr/bin/bash
### DEBDROID v3.08.
### Made By WMCB Tech @wmcbtech30
### This script should not be modified at some cases
### Dependencies Required for this script to work
### proot, tar, wget, dialog, pulseaudio
###
### Rootfs Hosting - https://github.com/debuerreotype/docker-debian-artifacts

### Environment Variables
ROOTFS="$PREFIX/share/debdroid/rootfs"
CONFIG="$PREFIX/share/debdroid/config"
PATHBASE="/usr/local/bin:/usr/local/sbin:/usr/local/games:/usr/bin:/usr/sbin:/usr/games:/bin:/sbin"
STATEFUL="$PREFIX/share/debdroid"
STATUS="$PREFIX/share/debdroid/rootfs/usr/lib/.libdone.so.9"
HOST_DISPLAY="$DISPLAY"
DEBDROID_BIND_HOME="$DEBDROID_BIND_HOME"

### Color Input Environment Variables
RED="$(tput setaf 1)"
GREEN="$(tput setaf 2)"
YELLOW="$(tput setaf 3)"
BOLD="$(tput bold)"
NOATTR="$(tput sgr0)"

set -e -u

## Root Detection
## Running This script as root will fail and mess up permissions
## And Prevent this script to run inside fakeroot also
if [[ $EUID -eq 0 ]]; then
	echo "${RED}${BOLD}This script should not be run as ROOT. please use linux deploy instead${NOATTR}" 1>&2
	exit 1
fi

check-network-connectivity(){
	if ping -q -c 1 -W 1 8.8.8.8 >/dev/null 2>&1; then
		exec
	else
		echo "${RED}${BOLD}Cannot connect to network. Try Checking your network connection. Aborting exit code 2${NOATTR}"
		exit 2
	fi
}

set-suite(){
	case `echo $SUITE` in
		oldstable|stretch)
			flavor="stretch" ;;
		stable|buster)
			flavor="buster" ;;
		testing|bullseye)
			flavor="testing" ;;
		unstable|sid)
			flavor="sid" ;;
		*)
			flavor="buster" ;;
	esac
}

check-dlcache() {
	if [ -e $HOME/.cache/dlcache-$flavor.tar.*z ]; then
		echo "${GREEN}${BOLD}Distribution Chosen: ${YELLOW}${flavor}${NOATTR}"
		echo ""
		echo "${GREEN}${BOLD}Existing Image File Found. Skipping Download and Extracting the rootfs${NOATTR}"
		echo "${GREEN}${BOLD}Unpacking The Base System.... This may take a few minutes${NOATTR}"
		proot --link2symlink -0 tar --preserve-permissions --delay-directory-restore -xf $HOME/.cache/dlcache-$flavor.tar.*z --exclude dev -C $ROOTFS >$PREFIX/tmp/debdroid-tar.log 2>&1 || true
	else
		echo "${GREEN}${BOLD}Downloading the Debian Image file: ${YELLOW}${flavor}${NOATTR}"
		echo ""
		mkdir -p $HOME/.cache >/dev/null 2>&1 &&
		wget "https://github.com/debuerreotype/docker-debian-artifacts/raw/${archurl}/${flavor}/rootfs.tar.xz" -O $HOME/.cache/dlcache-$flavor.tar.xz &&
		echo ""
		echo "${GREEN}${BOLD}Unpacking The Base System.... This may take a few minutes${NOATTR}"
		proot --link2symlink -0 tar --preserve-permissions --delay-directory-restore -xf $HOME/.cache/dlcache-$flavor.tar.*z --exclude dev -C $ROOTFS >$PREFIX/tmp/debdroid-tar.log 2>&1 || true
	fi
}

show_help(){
	echo "${BOLD}${GREEN}DebDroid: An Easy to Use Debian Installer for non-rooted devices"
	echo ""
	echo "Usage: debdroid [command]"
	echo ""
	echo " ${YELLOW}--install	${GREEN}Installs an Debian Distribution"
	echo " ${YELLOW}--uninstall	${GREEN}Uninstalls a Debian Distribution"
	echo " ${YELLOW}--reinstall	${GREEN}Reinstalls a Debian Distribution"
	echo " ${YELLOW}--launch	${GREEN}Launches Debian Distribution as Regular User (alias to ${YELLOW}--login${GREEN})"
	echo " ${YELLOW}--launch-su	${GREEN}Launches Debian Distribution as Root (alias to ${YELLOW}--login-as-root${GREEN})"
	echo " ${YELLOW}--isolated	${GREEN}Launches Debian Distribution without host storage access (alias to ${YELLOW}--launch-isolated${GREEN} or ${YELLOW}--login-isolated${GREEN})"
	echo " ${YELLOW}--import	${GREEN}Imports the Debian Container Image"
	echo " ${YELLOW}--export	${GREEN}Exports the Debian Container Image"
	echo " ${YELLOW}--status	${GREEN}Check if DebDroid is Installed"
	echo ""
	echo "To Pass Command within DebDroid. use the '--' option or '---' if isolated"
	echo "e.g.:"
	echo "	${YELLOW}debdroid -- sudo apt update"
	echo "	debdroid -- nano"
	echo "	debdroid --- sudo apt upgrade${GREEN}"
	echo ""
	echo "Alternatively is to use ${YELLOW}--exec${GREEN} or ${YELLOW}--exec-isolated${GREEN} if running in an isolated instance"
	echo ""
	echo "File Sharing Options:"
	echo " ${YELLOW}--send		${GREEN}Sends file/folder to user's home directory (alias to ${YELLOW}--push${GREEN})"
	echo " ${YELLOW}--recieve	${GREEN}Gets file/folder from the container (alias to ${YELLOW}--pull${GREEN})"
	echo ""
	echo "Sharing Examples: "
	echo "	${YELLOW}debdroid --send /sdcard/code.py"
	echo "	debdroid --recieve /opt/code.py"
	echo "	debdroid --pull /etc/profits/pygtk.c${GREEN}"
	echo "Pushed files will be placed on your home directory by default"
	echo ""
	echo "If you need to use Termux Home as Home Directory"
	echo "Specify ${YELLOW}DEBDROID_BIND_HOME=y${GREEN} Environment Variable"
	echo ""
	echo "Supported Distributions: "
	echo "${YELLOW}${BOLD}unstable/sid, stable/buster oldstable/stretch testing/bullseye"
	echo "${GREEN}${BOLD}You can Install them by typing: "
	echo ""
	echo "	debdroid --install ${YELLOW}${BOLD}<suite>"
	echo ""
	echo "${GREEN}${BOLD}If No Suite is specified. then it will install the stable one"
	echo "NOTE: Sid/Testing Versions may tend to fail the installation${NOATTR}"
}

exitcode(){
	echo ""
	echo "${RED}Exiting as Requested... Probably Installation Interruption"
	echo "To fix this. please run ${YELLOW}debdroid --uninstall${RED} and rerun the install command again${NOATTR}"
	echo ""
	exit 2
}

check-install-ok() {
	if bash $CONFIG/configure.sh; then
		rm $ROOTFS/opt/distro-config.sh || true
		echo "${GREEN}${BOLD}Debian Container successfully installed. All has gone well, to start the container type:"
		echo "${YELLOW}${BOLD}debdroid --launch${NOATTR}"
		exit 0
	else
		rm $ROOTFS/opt/distro-config.sh || true
		echo "${RED}${BOLD}One or more errors occured during the installation"
		echo "Possible causes are Incomplete Rootfs Download, Incomplete apt install, invalid username or Broken packages in sid/testing"
		echo ""
		echo "To correct this problem. Please reinstall it or choose the stable suite${NOATTR}"
		exit 2
	fi
}

install-debian() {
	SUITE="$@"
	trap 'exitcode' HUP INT QUIT TERM KILL
	if [ -e $STATUS ]; then
    		echo "${RED}${BOLD}An Existing Installation Found. Please Uninstall a Distro First${NOATTR}"
			exit 2
	else
    		echo "${GREEN}${BOLD}Preparing to Install a Debian Container.${NOATTR}"
	fi
	### Check Network
	check-network-connectivity
	### Check for an Architecture
	case `uname -m` in
		aarch64|arm64)
			archurl="dist-arm64v8" ;;
		arm|armv7l|armv8l)
			archurl="dist-arm32v7" ;;
		amd64|x86_64)
			archurl="dist-amd64" ;;
		x86|i*86)
			archurl="dist-i386" ;;
		*)
			echo "${RED}${BOLD}unknown architecture${NOATTR}"; exit 1 ;;
	esac
	set-suite
	check-dlcache
	echo "${GREEN}${BOLD}Configuring the Base System.. This may take Several Minutes${NOATTR}"
	echo ""
	set-android-groups || true
	install $CONFIG/libstat.so $ROOTFS/proc/stat &&
	install $CONFIG/libversion.so $ROOTFS/proc/version &&
	install $CONFIG/libvmstat.so $ROOTFS/proc/vmstat &&
	install $CONFIG/libuptime.so $ROOTFS/proc/uptime &&
	install $CONFIG/libloadavg.so $ROOTFS/proc/loadavg &&
	install $CONFIG/libresolv.conf.so $ROOTFS/etc/resolv.conf &&
	install $CONFIG/libhosts.so $ROOTFS/etc/hosts &&
	install $CONFIG/libdone.so.9 $ROOTFS/usr/lib/.libdone.so.9 &&
	install -m 755 $CONFIG/distro-config.sh $ROOTFS/opt/distro-config.sh &&
	mkdir $ROOTFS/proc/sys/kernel -p &&
	echo "0" > $ROOTFS/proc/sys/kernel/cap_last_cap &&
	echo "$flavor" > $ROOTFS/.proot.distinfo &&
	check-install-ok
}

reinstall() {
	if [ -e $STATUS ]; then
    	:
	else
		echo "${RED}${BOLD}Cannot Reinstall Debian Container. Container isn't installed${NOATTR}"
		exit 2
	fi
	SUITE="$(cat $ROOTFS/.proot.distinfo)"
	uninstall || true
	trap 'exitcode' HUP INT QUIT TERM KILL
	if [ -e $STATUS ]; then
    		echo "${RED}${BOLD}An Existing Installation Found. Please Uninstall a Distro First${NOATTR}"
			exit 2
	else
    		echo "${GREEN}${BOLD}Preparing to Install a Debian Container.${NOATTR}"
	fi
	### Check Network
	check-network-connectivity
	### Check for an Architecture
	case `uname -m` in
		aarch64|arm64)
			archurl="dist-arm64v8" ;;
		arm|armv7l|armv8l)
			archurl="dist-arm32v7" ;;
		amd64|x86_64)
			archurl="dist-amd64" ;;
		x86|i*86)
			archurl="dist-i386" ;;
		*)
			echo "${RED}${BOLD}unknown architecture${NOATTR}"; exit 1 ;;
	esac
	set-suite
	check-dlcache
	echo "${GREEN}${BOLD}Configuring the Base System.. This may take Several Minutes${NOATTR}"
	echo ""
	set-android-groups || true
	install $CONFIG/libstat.so $ROOTFS/proc/stat &&
	install $CONFIG/libversion.so $ROOTFS/proc/version &&
	install $CONFIG/libvmstat.so $ROOTFS/proc/vmstat &&
	install $CONFIG/libuptime.so $ROOTFS/proc/uptime &&
	install $CONFIG/libloadavg.so $ROOTFS/proc/loadavg &&
	install $CONFIG/libresolv.conf.so $ROOTFS/etc/resolv.conf &&
	install $CONFIG/libhosts.so $ROOTFS/etc/hosts &&
	install $CONFIG/libdone.so.9 $ROOTFS/usr/lib/.libdone.so.9 &&
	install -m 755 $CONFIG/distro-config.sh $ROOTFS/opt/distro-config.sh &&
	echo "$flavor" > $ROOTFS/.proot.distinfo &&
	mkdir $ROOTFS/proc/sys/kernel -p &&
	echo "0" > $ROOTFS/proc/sys/kernel/cap_last_cap &&
	check-install-ok
}

uninstall() {
	echo "${RED}${BOLD}WARNING: you are about to uninstall a linux distribution in 10 seconds${NOATTR}"
	echo "${RED}${BOLD}to stop hit Ctrl-C before Uninstallation${NOATTR}"
	sleep 10 &&
	echo "${YELLOW}Uninstalling an Linux Distro...${NOATTR}"
	chmod 777 -R $ROOTFS > /dev/null 2>&1 || true
	rm -rf $STATEFUL/rootfs > /dev/null 2>&1 &&
	mkdir $STATEFUL/rootfs > /dev/null 2>&1 &&
	echo "${GREEN}${BOLD}Debian Container Successfully Uninstalled${NOATTR}"
}

set-android-groups(){
	### This should atleast fix group errors for Ubuntu Guests
	echo "aid_$(id -un):x:$(id -u):$(id -g):Android Groups:/:/usr/sbin/nologin" >> "$ROOTFS/etc/passwd"
	echo "aid_$(id -un):*:18446:0:99999:7:::" >> "$ROOTFS/etc/shadow"
	local g
		for g in $(id -G); do
			echo "aid_$(id -gn "$g"):x:${g}:root,aid_$(id -un)" >> "$ROOTFS/etc/group"
			if [ -f "$ROOTFS/etc/gshadow" ]; then
				echo "aid_$(id -gn "$g"):*::root,aid_$(id -un)" >> "$ROOTFS/etc/gshadow"
			fi
		done
}

send() {
	SEND_ARGS="$@"
	if [ -e $STATUS ]; then
		:
	else
		echo "${RED}${BOLD}Cannot stat Debian Container. Please install it using ${YELLOW}debdroid --install${NOATTR}"
		exit 2
	fi
	### Check for an Argument
	if [ ! -z "$SEND_ARGS" ]; then
		:
	else
		echo "${RED}${BOLD}Please Specify a File/Folder to Send${NOATTR}"
		exit 2
	fi
	### Check for a file to Send
	if [ ! -e "$SEND_ARGS" ]; then
		echo "${RED}${BOLD}Cannot Send file to the Container: No Such file or Directory${NOATTR}"
		exit 2
	fi
	### Send files
	echo "${YELLOW}${BOLD}Sending File: $SEND_ARGS ${NOATTR}"
	cp -rf "$SEND_ARGS" $ROOTFS/home/$(cat $ROOTFS/etc/userinfo.rc)/ >/dev/null 2>&1 || true
	echo "${GREEN}${BOLD}The File "$SEND_ARGS" successfully sent at your Home Directory${NOATTR}"
}

recieve(){
	RECIEVE_ARGS="$@"
	local PWD="$(pwd)"
	if [ -e $STATUS ]; then
		:
	else
		echo "${RED}${BOLD}Cannot stat Debian Container. Please install it using ${YELLOW}debdroid --install${NOATTR}"
		exit 2
	fi
	### Check for an Argument
	if [ ! -z "$RECIEVE_ARGS" ]; then
		:
	else
		echo "${RED}${BOLD}Please Specify an File/Folder to pull${NOATTR}"
		exit 2
	fi
	### Check for an File to pull
	if [ ! -e "${ROOTFS}${RECIEVE_ARGS}" ]; then
		echo "${RED}${BOLD}Cannot Pull a file from the container: no such file or directory${NOATTR}"
		exit 2
	fi
	### Pull Files
	echo "${YELLOW}${BOLD}Pulling $RECIEVE_ARGS...${NOATTR}" 
	cp -rf "${ROOTFS}${RECIEVE_ARGS}" "$PWD" >/dev/null 2>&1 || true
}

update_display_environment(){
	cat > $ROOTFS/etc/profile.d/debdroid-host-display.sh <<- EOM
	export DISPLAY="$HOST_DISPLAY"
	EOM
}

launch() {
	local SHARE_PROPERTIES=""
	if [ -e $STATUS ]; then
    	:
	else
		echo "${RED}${BOLD}Cannot start Debian Container. Please install it using ${YELLOW}debdroid --install${NOATTR}"
		exit 2
	fi
	### Check if DEBDROID_BIND_HOME is specified
	if [ "$DEBDROID_BIND_HOME" == "y" ]; then
		export CONFIG_BIND_HOME=" -b $HOME:/home/$(cat $ROOTFS/etc/userinfo.rc) -b $HOME:/root "
	else
		export CONFIG_BIND_HOME=""
	fi
	unset LD_PRELOAD
	start-pulseaudio
	update_display_environment
	proot --link2symlink --kill-on-exit \
	-0 -r $ROOTFS -p --sysvipc -H -k 4.14.206 \
	$CONFIG_BIND_HOME \
	-b /dev \
	-b /proc \
	-b /sys \
	-b /dev/urandom:/dev/random \
	-b /proc/self/fd:/dev/fd \
	-b /proc/self/fd/0:/dev/stdin \
	-b /proc/self/fd/1:/dev/stdout \
	-b /proc/self/fd/2:/dev/stderr \
	-b $PREFIX/tmp:/dev/shm \
	-b $PREFIX/tmp:/tmp \
	-b $ROOTFS/proc/stat:/proc/stat \
	-b $ROOTFS/proc/version:/proc/version \
	-b $ROOTFS/proc/uptime:/proc/uptime \
	-b $ROOTFS/proc/vmstat:/proc/vmstat \
	-b $ROOTFS/proc/loadavg:/proc/loadavg \
	-b $ROOTFS/proc/sys/kernel/cap_last_cap:/proc/sys/kernel/cap_last_cap \
	-b /storage/emulated/0:/sdcard \
	-b /:/host-rootfs -b /system -b /data -b /storage \
	-w /root \
	/usr/bin/env -i \
	TERM=xterm-256color \
	HOME=/root \
	USER=root \
	PATH="$PATHBASE" \
	TMPDIR=/tmp \
	LANG=C.UTF-8 \
	/bin/su -l $(cat $ROOTFS/etc/userinfo.rc) || true
	:
	exec stop-pulseaudio || true
}

launch-su() {
	local SHARE_PROPERTIES=""
	if [ -e $STATUS ]; then
    	:
	else
		echo "${RED}${BOLD}Cannot start Debian Container. Please install it using ${YELLOW}debdroid --install${NOATTR}"
		exit 2
	fi
	### Check if DEBDROID_BIND_HOME is specified
	if [ "$DEBDROID_BIND_HOME" == "y" ]; then
		export CONFIG_BIND_HOME=" -b $HOME:/home/$(cat $ROOTFS/etc/userinfo.rc) -b $HOME:/root "
	else
		export CONFIG_BIND_HOME=""
	fi
	unset LD_PRELOAD
	start-pulseaudio
	update_display_environment
	proot --link2symlink --kill-on-exit \
	-0 -r $ROOTFS -p --sysvipc -H -k 4.14.206 \
	$CONFIG_BIND_HOME \
	-b /dev \
	-b /proc \
	-b /sys \
	-b /dev/urandom:/dev/random \
	-b /proc/self/fd:/dev/fd \
	-b /proc/self/fd/0:/dev/stdin \
	-b /proc/self/fd/1:/dev/stdout \
	-b /proc/self/fd/2:/dev/stderr \
	-b $PREFIX/tmp:/dev/shm \
	-b $PREFIX/tmp:/tmp \
	-b $ROOTFS/proc/stat:/proc/stat \
	-b $ROOTFS/proc/version:/proc/version \
	-b $ROOTFS/proc/uptime:/proc/uptime \
	-b $ROOTFS/proc/vmstat:/proc/vmstat \
	-b $ROOTFS/proc/loadavg:/proc/loadavg \
	-b $ROOTFS/proc/sys/kernel/cap_last_cap:/proc/sys/kernel/cap_last_cap \
	-b /storage/emulated/0:/sdcard \
	-b /:/host-rootfs -b /system -b /data -b /storage \
	-w /root \
	/usr/bin/env -i \
	TERM=xterm-256color \
	HOME=/root \
	USER=root \
	PATH="$PATHBASE" \
	TMPDIR=/tmp \
	LANG=C.UTF-8 \
	/bin/su -l || true
	:
	exec stop-pulseaudio || true
}

launch-isol() {
	if [ -e $STATUS ]; then
    	:
	else
		echo "${RED}${BOLD}Cannot start Debian Container. Please install it using ${YELLOW}debdroid --install${NOATTR}"
		exit 2
	fi
	unset LD_PRELOAD
	start-pulseaudio
	update_display_environment
	proot --link2symlink --kill-on-exit \
	-0 -r $ROOTFS -p --sysvipc -H -k 4.14.206 \
	-b /dev \
	-b /proc \
	-b /sys \
	-b /proc/self/fd:/dev/fd \
	-b /proc/self/fd/0:/dev/stdin \
	-b /proc/self/fd/1:/dev/stdout \
	-b /proc/self/fd/2:/dev/stderr \
	-b $ROOTFS/tmp:/dev/shm \
	-b $ROOTFS/proc/stat:/proc/stat \
	-b $ROOTFS/proc/version:/proc/version \
	-b $ROOTFS/proc/uptime:/proc/uptime \
	-b $ROOTFS/proc/vmstat:/proc/vmstat \
	-b $ROOTFS/proc/loadavg:/proc/loadavg \
	-b $ROOTFS/proc/sys/kernel/cap_last_cap:/proc/sys/kernel/cap_last_cap \
	-w /root \
	/usr/bin/env -i \
	TERM=xterm-256color \
	HOME=/root \
	USER=root \
	PATH="$PATHBASE" \
	TMPDIR=/tmp \
	LANG=C.UTF-8 \
	/bin/su -l $(cat $ROOTFS/etc/userinfo.rc) || true
	:
	exec stop-pulseaudio || true
}

parse-cmd() {
	local SHARE_PROPERTIES=""
	if [ -e $STATUS ]; then
    	:
	else
		echo "${RED}${BOLD}Cannot start Debian Container. Please install it using ${YELLOW}debdroid --install${NOATTR}"
		exit 2
	fi
	### Check if DEBDROID_BIND_HOME is specified
	if [ "$DEBDROID_BIND_HOME" == "y" ]; then
		export CONFIG_BIND_HOME=" -b $HOME:/home/$(cat $ROOTFS/etc/userinfo.rc) -b $HOME:/root "
	else
		export CONFIG_BIND_HOME=""
	fi
	unset LD_PRELOAD
	update_display_environment
	proot --link2symlink --kill-on-exit \
	-0 -r $ROOTFS -p --sysvipc -H -k 4.14.206 \
	$CONFIG_BIND_HOME \
	-b /dev \
	-b /proc \
	-b /sys \
	-b /dev/urandom:/dev/random \
	-b /proc/self/fd:/dev/fd \
	-b /proc/self/fd/0:/dev/stdin \
	-b /proc/self/fd/1:/dev/stdout \
	-b /proc/self/fd/2:/dev/stderr \
	-b $PREFIX/tmp:/dev/shm \
	-b $PREFIX/tmp:/tmp \
	-b $ROOTFS/proc/stat:/proc/stat \
	-b $ROOTFS/proc/version:/proc/version \
	-b $ROOTFS/proc/uptime:/proc/uptime \
	-b $ROOTFS/proc/vmstat:/proc/vmstat \
	-b $ROOTFS/proc/loadavg:/proc/loadavg \
	-b $ROOTFS/proc/sys/kernel/cap_last_cap:/proc/sys/kernel/cap_last_cap \
	-b /storage/emulated/0:/sdcard \
	-b /:/host-rootfs -b /system -b /data -b /storage \
	-w /root \
	/usr/bin/env -i \
	TERM=xterm-256color \
	HOME=/root \
	USER=root \
	PATH="$PATHBASE" \
	TMPDIR=/tmp \
	LANG=C.UTF-8 \
	sudo -i -u $(cat $ROOTFS/etc/userinfo.rc) "$@"
}

parse-cmd-isol() {
	if [ -e $STATUS ]; then
    	:
	else
		echo "${RED}${BOLD}Cannot start Debian Container. Please install it using ${YELLOW}debdroid --install${NOATTR}"
		exit 2
	fi
	unset LD_PRELOAD
	update_display_environment
	proot --link2symlink --kill-on-exit \
	-0 -r $ROOTFS -p --sysvipc -H -k 4.14.206 \
	-b /dev \
	-b /proc \
	-b /sys \
	-b /proc/self/fd:/dev/fd \
	-b /proc/self/fd/0:/dev/stdin \
	-b /proc/self/fd/1:/dev/stdout \
	-b /proc/self/fd/2:/dev/stderr \
	-b $ROOTFS/tmp:/dev/shm \
	-b $ROOTFS/proc/stat:/proc/stat \
	-b $ROOTFS/proc/version:/proc/version \
	-b $ROOTFS/proc/uptime:/proc/uptime \
	-b $ROOTFS/proc/vmstat:/proc/vmstat \
	-b $ROOTFS/proc/loadavg:/proc/loadavg \
	-b $ROOTFS/proc/sys/kernel/cap_last_cap:/proc/sys/kernel/cap_last_cap \
	-w /root \
	/usr/bin/env -i \
	TERM=xterm-256color \
	HOME=/root \
	USER=root \
	PATH="$PATHBASE" \
	TMPDIR=/tmp \
	LANG=C.UTF-8 \
	sudo -i -u $(cat $ROOTFS/etc/userinfo.rc) "$@"
}

check_status(){
	if [ -e $STATUS ]; then
		echo "${GREEN}${BOLD}Debian Container ${YELLOW}is Installed${NOATTR}"
		echo "${GREEN}${BOLD}Debian Version: ${YELLOW}$(cat $ROOTFS/.proot.distinfo)${NOATTR}"
		exit 0
	else
		echo "${RED}${BOLD}Debian Container ${YELLOW}isn't Installed${NOATTR}"
		exit 2
	fi
}

cleanup-tmp(){
	rm -rf $HOME/.cache/dlcache-* || true
}

if [ $# = 0 ]; then
	show_help
	exit 2
fi

CMD="$1"
shift 1

case "$CMD" in
	--install) install-debian "$@" ;;
	--uninstall)
		uninstall
		;;
	--reinstall)
		reinstall
		;;
	--launch|--login)
		launch
		;;
	--launch-su|--login-as-root)
		launch-su
		;;
	--launch-isolated|--isolated|--login-isolated)
		launch-isol
		;;
	--cleanup-tmp)
		cleanup-tmp
		;;
	--export)
		exec $STATEFUL/lib/libbackup-rootfs.so
		;;
	--import)
		exec $STATEFUL/lib/librestore-rootfs.so
		;;
	-h|--help|--show-help)
		show_help
		;;
	--send|--push)
		send "$@"
		;;
	--recieve|--pull)
		recieve "$@"
		;;
	--status)
		check_status
		;;
	--|--exec)
		parse-cmd "$@"
		;;
	---|--exec-isolated)
		parse-cmd-isol "$@"
		;;
	*) echo "${RED}Unknown Command: $CMD ${NOATTR}"; exit 2;;
esac
