#!/data/data/com.termux/files/usr/bin/bash

## Make a simple dialog to greet the users
dialog --title "Information" \
 --msgbox \
 "Welcome to DebDroid an easy debian installer. to learn more about debdroid\
  Please visit http://github.com/WMCB-Tech/DebDroid and it's features. if you have issues\
  please share it with Github or Discord" \
 13 40