# This is a basic workflow to help you get started with Actions

name: Shell Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 shellchecker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Shell Checker
        uses: ludeeus/action-shellcheck@master
